package cd.backend.codegen;

import java.io.Writer;
import java.util.List;

import cd.Config;
import cd.Main;
import cd.backend.codegen.RegisterManager.Register;
import cd.ir.Ast.ClassDecl;

public class AstCodeGenerator {

	protected RegsNeededVisitor rnv;
	
	protected ExprGenerator eg;
	protected StmtGenerator sg;
	
	protected final Main main;
	
	protected final AssemblyEmitter emit;
	protected final RegisterManager rm = new RegisterManager();
	
	protected static final String VAR_PREFIX = "var_";

	AstCodeGenerator(Main main, Writer out) {
		{
			initMethodData();
		}
		
		this.emit = new AssemblyEmitter(out);
		this.main = main;
		this.rnv = new RegsNeededVisitor();

		this.eg = new ExprGenerator(this);
		this.sg = new StmtGenerator(this);
	}

	protected void debug(String format, Object... args) {
		this.main.debug(format, args);
	}

	public static AstCodeGenerator createCodeGenerator(Main main, Writer out) {
		return new AstCodeGenerator(main, out);
	}
	
	
	/**
	 * Main method. Causes us to emit x86 assembly corresponding to {@code ast}
	 * into {@code file}. Throws a {@link RuntimeException} should any I/O error
	 * occur.
	 * 
	 * <p>
	 * The generated file will be divided into two sections:
	 * <ol>
	 * <li>Prologue: Generated by {@link #emitPrefix()}. This contains any
	 * introductory declarations and the like.
	 * <li>Body: Generated by {@link ExprGenerator}. This contains the main
	 * method definitions.
	 * </ol>
	 */
	VTableManager vtableManager;		
	ObjectShapeManager objShapeManager;
	public void go(List<? extends ClassDecl> astRoots) {
		
		// TODO: rewrite these 2 classes
		vtableManager = new VTableManager(astRoots, this);		
		objShapeManager = new ObjectShapeManager(astRoots, vtableManager);
		
		emit.emitRaw(Config.DATA_INT_SECTION);
		vtableManager.emit();
		
		// Emit some useful string constants:
		emit.emitLabel("\tSTR_NL");
		emit.emitRaw("\t\t" + Config.DOT_STRING + " \"\\n\"");
		emit.emitLabel("\tSTR_D");
		emit.emitRaw("\t\t" + Config.DOT_STRING + " \"%d\"");
		
		emit.emitRaw(Config.TEXT_SECTION);
		emit.emit(".global", Config.MAIN);
		emit.emitRaw("");
		emit.emitLabel(Config.MAIN);
		
		//get the vtable
		VTable table = vtableManager.get("Main");
		
		//get the size and layout
		ObjectShape objShape = objShapeManager.get("Main");
				
		emit.emit("pushl", "$4");
		emit.emit("pushl", "$"+objShape.sizeInN());
		emit.emit("call", "calloc");
		emit.emit("movl", "$"+objShape.getAddr(), "(%eax)");
		
		String label = table.getLabel("main").toString();
		
		emit.emit("movl", "%eax", "(%esp)");	//set the receiver of main
		emit.emit("call", label);			//call main
		emit.emit("addl", "$4", "%esp");
		emit.emitRaw("ret");
		
		for (ClassDecl ast : astRoots) {
			sg.gen(ast);
		}
	}
	
	protected void initMethodData() {
		{
			rm.initRegisters();
		}
	}


	protected void emitMethodSuffix(boolean returnNull) {
		if (returnNull)
			emit.emit("movl", "$0", Register.EAX);
		emit.emitRaw("leave");
		emit.emitRaw("ret");
	}
}